stages:
  - build
  - test
  - deploy

build_backend:
  stage: build
  only:
    - master
    - CI
  tags:
    - nodejs
  script:
    - cd backend
    - npm install
    - npm run prod
  artifacts:
    paths:
      - backend/dist

build_frontend:
  stage: build
  only:
    - master
    - CI
  tags:
    - nodejs
  script:
    - cd frontend
    - npm install
    - npm run prod
  artifacts:
    paths:
      - frontend/dist

test:
  stage: test
  tags:
    - nodejs
  script:
    - cd backend
    - npm install
    - npm test

deploy:
  stage: deploy
  only:
    - master
    - CI
  tags:
    - ssh
  dependencies:
    - build_backend
    - build_frontend
  script:
    - chmod -R a+rX,ug+w backend
    - chmod -R a+rX,ug+w frontend
    - eval $(ssh-agent -s)
    - mkdir ~/.ssh && echo "$STAGING_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - ssh-add <(echo "$STAGING_SSH_PRIVATE_KEY")
    - rm -rf backend/src
    - scp -r backend/* "$STAGING_BACKEND_SSH_URL"
    - scp -r frontend/dist/* "$STAGING_FRONTEND_SSH_URL"

